name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish Rest
      uses: brandedoutcast/publish-nuget@v2.5.5
      with:   
        PROJECT_FILE_PATH: ARSolution.OpenHAB.Rest/ARSolution.OpenHAB.Rest.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
    - name: Publish Model
      uses: brandedoutcast/publish-nuget@v2.5.5  
      with:   
        PROJECT_FILE_PATH: ARSolution.OpenHAB.Model/ARSolution.OpenHAB.Model.csproj  
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}  
